spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/maple_bill?useUnicode=true&characterEncoding=utf8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  h2:
    console:
      enabled: true
  flyway:
    # 如果启动的时候需要flyway管理sql脚本的话，将enabled设置为true
#    这里设置为false，是因为要自动创建数据库，并且在jpa创建表后才启用flyway
    enabled: false
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    # 验证错误时 是否自动清除数据库 高危操作!
    clean-on-validation-error: false
